version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --port 6379 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: